//
//  Products.swift
//  GoldenShoe
//
//  Created by Nathan Strickland on 06/01/2021.
//

import Foundation

// swiftlint:disable line_length
// swiftlint:disable type_body_length
class Products {
  // Mock Store Data
  private let products: [Product] = [
    Product(favourited: false, productID: 0, filters: ["category": "womens", "type": "boots", "style": "alternative"], shortDescription: "Black 1460 8 Eye Boots", longDescription: "Dr. Martens created this classic 8 Tie boot in 1960 and it has since gone on to gain legendary status in nearly every decade thanks to its timeless style and cult following. A leather upper with the trademark yellow stitching sits on an AirWair sole. ", brand: "Dr Martens", color: "Black", price: "£149.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/140719/1407197020_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/140719/1407197020m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/140719/1407197020m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/140719/1407197020m7_zm.jpg"]),
    Product(favourited: false, productID: 1, filters: ["category": "womens", "type": "boots", "style": "alternative"], shortDescription: "1460 8 Eye", longDescription: "Bringing all the pink onto your radar! The Dr. Martens 1460 8 Eye Boot boasts a pink leather upper sat on a trusty AirWair sole to give every step some bounce. Complete with branding. ", brand: "Dr Martens", color: "Pink", price: "£149.00", onSale: true, salePrice: "£119.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/144768/1447683520_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/144768/1447683520m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/144768/1447683520m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/144768/1447683520m7_zm.jpg"]),
    Product(favourited: false, productID: 2, filters: ["category": "womens", "type": "boots", "style": "alternative"], shortDescription: "1460 8 Eye", longDescription: "Get bold and bright this season with the latest Dr. Martens. The 1460 8 Eye Boot boasts a light green leather upper in its classic silhouette that brings edge to any look. Complete with classic yellow stitching. ", brand: "Dr Martens", color: "Light Green", price: "£149.00", onSale: true, salePrice: "£104.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/144768/1447688020_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/144768/1447688020m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/144768/1447688020m7_zm.jpg"]),
    Product(favourited: false, productID: 3, filters: ["category": "womens", "type": "boots", "style": "biker"], shortDescription: "Black Aubrey Fur Biker Boots", longDescription: "Let's get cosy. The Aubrey Fur Biker Boot boasts a black man-made upper lined with soft and insulating faux-fur for a real comfy finish. This fit keeps it real stylish through the winter months. ", brand: "Golden Shoe", color: "Black", price: "£40.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/142964/1429647060_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/142964/1429647060m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/142964/1429647060m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/142964/1429647060m7_zm.jpg"]),
    Product(favourited: false, productID: 4, filters: ["category": "womens", "type": "boots", "style": "biker"], shortDescription: "Brown Lorna Boots", longDescription: "Made to handle the new season, Lorna arrives from UGG. This calf-length boot keeps you cosy with a fluffy wool lining while the brown leather and suede upper keeps it versatile. Buckle straps add a bit of attitude.", brand: "UGG", color: "Brown", price: "£175.00", onSale: true, salePrice: "£129.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/148352/1483526020_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/148352/1483526020m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/148352/1483526020m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/148352/1483526020m7_zm.jpg"]),
    Product(favourited: false, productID: 5, filters: ["category": "womens", "type": "boots", "style": "casual ankle"], shortDescription: "Black Charlotte Point Chelsea Boots", longDescription: "Landing in black, the Charlotte chelsea boot from Golden Shoe is your new boot obsession. Featuring a block heel, pointed toe and elasticated side panels, this is the style that will go with everything. ", brand: "Golden Shoe", color: "Black", price: "£35.00", onSale: true, salePrice: "£19.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/142244/1422447060_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/142244/1422447060m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/142244/1422447060m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/142244/1422447060m7_zm.jpg"]),
    Product(favourited: false, productID: 6, filters: ["category": "womens", "type": "boots", "style": "casual ankle"], shortDescription: "Tan Release Leather Chelsea Boots", longDescription: "The humble leather Chelsea boot - you just can't beat it. Check this one out from the latest Golden Shoe collection. The Release boasts a tan leather upper and a sturdy sole. ", brand: "Golden Shoe", color: "Tan", price: "£45.00", onSale: true, salePrice: "£29.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/143897/1438976220_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/143897/1438976220m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/143897/1438976220m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/143897/1438976220m7_zm.jpg"]),
    Product(favourited: false, productID: 7, filters: ["category": "womens", "type": "boots", "style": "casual ankle"], shortDescription: "Black Aubrey Fur Biker Boots", longDescription: "Let's get cosy. The Aubrey Fur Biker Boot boasts a black man-made upper lined with soft and insulating faux-fur for a real comfy finish. This fit keeps it real stylish through the winter months. ", brand: "Golden Shoe", color: "Black", price: "£40.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/142964/1429647060_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/142964/1429647060m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/142964/1429647060m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/142964/1429647060m7_zm.jpg"]),
    Product(favourited: false, productID: 8, filters: ["category": "womens", "type": "boots", "style": "casual ankle"], shortDescription: "Tan Revision Leather Lace Up Boots", longDescription: "The Red Or Dead autumn collection has landed! The Revision Leather Lace Up boot arrives in a soft tan upper with a block heel to elevate your look. This simple yet oh-so stylish fit is destined for your wardrobe. ", brand: "Red Or Dead", color: "Tan", price: "£90.00", onSale: true, salePrice: "£54.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/147471/1474716220_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/147471/1474716220m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/147471/1474716220m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/147471/1474716220m7_zm.jpg"]),
    Product(favourited: false, productID: 9, filters: ["category": "womens", "type": "boots", "style": "casual ankle"], shortDescription: "Black Rita Chelsea Suede Boots", longDescription: "Get winter ready with Red Or Dead! The Rita Chelsea Suede boot makes moves in a black colourway paired with a chunky rubber outsole for grip and style. Go on...get the look. ", brand: "Red Or Dead", color: "Black", price: "£75.00", onSale: true, salePrice: "£44.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/147468/1474687050_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/147468/1474687050m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/147468/1474687050m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/147468/1474687050m7_zm.jpg"]),
    Product(favourited: false, productID: 10, filters: ["category": "womens", "type": "boots", "style": "casual ankle"], shortDescription: "Tan Classic Ultra Mini Boots", longDescription: "UGG is back and we're ready! The Classic Ultra Mini arrives in a tan suede upper with plenty of UGG Pure Wool to keep things cosy. This shorter style will upgrade any winter wardrobe. Complete with branding. ", brand: "UGG", color: "Tan", price: "£125.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/148376/1483766250_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/148376/1483766250m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/148376/1483766250m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/148376/1483766250m7_zm.jpg"]),
    Product(favourited: false, productID: 11, filters: ["category": "womens", "type": "boots", "style": "casual ankle"], shortDescription: "Dark Brown Scop Boots", longDescription: "Get your Fly London fix right here at Golden Shoe! The Scop boot boasts a sleek dark brown leather upper sat on a ribbed rubber outsole for grip on any adventure. Complete with branding embossed. ", brand: "Fly London", color: "Dark Brown", price: "£145.00", onSale: true, salePrice: "£104.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/154327/1543276120_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/154327/1543276120m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/154327/1543276120m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/154327/1543276120m7_zm.jpg"]),
    Product(favourited: false, productID: 12, filters: ["category": "womens", "type": "boots", "style": "casual ankle"], shortDescription: "Tan Caitlin Buckle Detail Chelsea Boots", longDescription: "Winter fits are in! The Caitlin Buckle Detail Chelsea Boot arrives in a versatile tan man-made upper with a block heel for sophisticated style. Buckle detail and elastic inserts complete. ", brand: "Golden Shoe", color: "Tan", price: "£25.00", onSale: true, salePrice: "£17.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/141225/1412256260_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/141225/1412256260m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/141225/1412256260m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/141225/1412256260m7_zm.jpg"]),
    Product(favourited: false, productID: 13, filters: ["category": "womens", "type": "boots", "style": "casual ankle"], shortDescription: "Burgundy Charly Vegan Boots", longDescription: "The latest Blowfish collection is here and we guarantee you'll be obsessed! The Charly Vegan boasts a burgundy man-made upper with a block heel for height and style. Complete with branding embossed. ", brand: "Blowfish Malibu", color: "Burgundy", price: "£60.00", onSale: true, salePrice: "£34.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/143967/1439673260_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/143967/1439673260m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/143967/1439673260m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/143967/1439673260m7_zm.jpg"]),
    Product(favourited: false, productID: 14, filters: ["category": "womens", "type": "boots", "style": "casual ankle"], shortDescription: "White Alexa Leather Chelsea Boots", longDescription: "Alexa, show me style! The Golden Shoe Alexa Leather Chelsea Boot lands in a white leather upper paired with a thick rubber outsole for style that'll last all winter. We love. ", brand: "Golden Shoe", color: "White", price: "£80.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/142942/1429421020_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/142942/1429421020m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/142942/1429421020m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/142942/1429421020m7_zm.jpg"]),
    Product(favourited: false, productID: 15, filters: ["category": "womens", "type": "boots", "style": "casual calf"], shortDescription: "Black Raexy Vegan Boots", longDescription: "Freshen up your winter rotation with the Blowfish Raexy Vegan boot! This fit boasts a black man-made upper with strap detailing and a slight heel. This fit is perfect for keeping you cosy and cute this season. ", brand: "Blowfish Malibu", color: "Black", price: "£70.00", onSale: true, salePrice: "£49.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/153279/1532797060_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/153279/1532797060m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/153279/1532797060m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/153279/1532797060m7_zm.jpg"]),
    Product(favourited: false, productID: 16, filters: ["category": "womens", "type": "boots", "style": "casual calf"], shortDescription: "Brown Raexy Vegan Boots", longDescription: "Make your winter fit vegan this year! The Blowfish Raexy Vegan boot arrives in a brown man-made upper with strap detailing to add some sophisticated and chic vibes. This fit is finished with branding. ", brand: "Blowfish Malibu", color: "Brown", price: "£70.00", onSale: true, salePrice: "£49.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/153279/1532796060_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/153279/1532796060m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/153279/1532796060m7_zm.jpg"]),
    Product(favourited: false, productID: 17, filters: ["category": "womens", "type": "boots", "style": "casual calf"], shortDescription: "Tan Radley Leather Hi Leg Boots", longDescription: "Looking for your next winter fit? We've got you covered! The Red Or Dead Radley Leather Hi Leg Boot arrives in a tan colourway in a knee-high silhouette to keep you cosy and stylish. Get the look. ", brand: "Red Or Dead", color: "Tan", price: "£110.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/151730/1517306220_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/151730/1517306220m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/151730/1517306220m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/151730/1517306220m7_zm.jpg"]),
    Product(favourited: false, productID: 18, filters: ["category": "womens", "type": "boots", "style": "casual calf"], shortDescription: "Tan Classic Mini Bow II Boots", longDescription: "Landing in a must-have tan colourway, the Classic Mini Bow II from UGG is the winter staple you've been waiting for. The Classic boot you know and love has been reimagined with a bow added to the back for maximum style. ", brand: "UGG", color: "Tan", price: "£155.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/148381/1483816250_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/148381/1483816250m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/148381/1483816250m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/148381/1483816250m7_zm.jpg"]),
    Product(favourited: false, productID: 19, filters: ["category": "womens", "type": "boots", "style": "casual calf"], shortDescription: "Tan Darlene Leather Riding Boots", longDescription: "Give 2020 the boot and upgrade your rotation now! The Darlene Leather Riding Boot lands in a premium tan leather upper paired with buckle details and slight heel. This fit will freshen up any winter wardrobe, trust us. ", brand: "Golden Shoe", color: "Tan", price: "£80.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/158151/1581516220_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/158151/1581516220m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/158151/1581516220m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/158151/1581516220m7_zm.jpg"]),
    Product(favourited: false, productID: 20, filters: ["category": "womens", "type": "boots", "style": "casual knee"], shortDescription: "Black Daz Pointed Over the Knee Boots", longDescription: "Walk into the new season with the ultimate pair of new boots. The Daz pointed over the knee boots boast a black suedette/microfiber upper with a chic block heel. This silhouette will make an impact on any fit. ", brand: "Golden Shoe", color: "Black", price: "£55.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/158102/1581027060_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/158102/1581027060_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/158102/1581027060m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/158102/1581027060m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/158102/1581027060m7_zm.jpg"]),
    Product(favourited: false, productID: 21, filters: ["category": "womens", "type": "boots", "style": "casual knee"], shortDescription: "Tan Drake Suede Pull On Boots", longDescription: "Your next winter fit is right here at Golden Shoe! The Drake Suede Pull On Boot boasts a rich tan colourway in an over-the-knee silhouette with a block heel. This fit is definitely a must-have this season. ", brand: "Golden Shoe", color: "Tan", price: "£120.00", onSale: true, salePrice: "£84.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/152381/1523816250_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/152381/1523816250_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/152381/1523816250m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/152381/1523816250m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/152381/1523816250m7_zm.jpg"]),
    Product(favourited: false, productID: 22, filters: ["category": "womens", "type": "boots", "style": "outdoor"], shortDescription: "Natural 6 Inch Premium Boots", longDescription: "An iconic design built for the great outdoors, the Timberland 6-inch Premium boot features a natural nubuck upper, thick rubber traction sole, padded ankle collar and metal eyelets. This 90s inspired profile is finished with embossed branding on the heel. ", brand: "Timberland", color: "Natural", price: "£180.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/140060/1400601430_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/140060/1400601430m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/140060/1400601430m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/140060/1400601430m7_zm.jpg"]),
    Product(favourited: false, productID: 23, filters: ["category": "womens", "type": "boots", "style": "outdoor"], shortDescription: "Tan Allington Boots", longDescription: "Adding a bit of extra height to this classic boot, Timberland create a feminine profile fit for your everyday wardrobe. The Allington lace-up features an elegant tan nubuck upper with brown leather ankle collar, two-tone laces and an 8cm heel to complete. ", brand: "Timberland", color: "Tan", price: "£120.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/147948/1479486230_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/147948/1479486230m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/147948/1479486230m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/147948/1479486230m7_zm.jpg"]),
    Product(favourited: false, productID: 24, filters: ["category": "womens", "type": "boots", "style": "outdoor"], shortDescription: "Black Wynter Black Wellington Boots", longDescription: "It's officially wellie weather! The Wynter Black Wellington boasts a black man-made upper that's thick and strong to get you through the winter months. Puddle-proof, obviously. ", brand: "Golden Shoe", color: "Black", price: "£20.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/146470/1464707060_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/146470/1464707060m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/146470/1464707060m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/146470/1464707060m7_zm.jpg"]),
    Product(favourited: false, productID: 25, filters: ["category": "womens", "type": "boots", "style": "outdoor"], shortDescription: "Black & Gold Wilma Leopard Wellington Boots", longDescription: "Welly weather is here! The OO Wilma Leopard Wellington arrives in a black and gold man-made upper paired with some sparkle for added bling! Do it in style. ", brand: "Golden Shoe", color: "Black & Gold", price: "£18.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/146472/1464727960_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/146472/1464727960m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/146472/1464727960m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/146472/1464727960m7_zm.jpg"]),
    Product(favourited: false, productID: 26, filters: ["category": "womens", "type": "heels", "style": "casual courts"], shortDescription: "Black Sky Patent Croc Point High Heels", longDescription: "Pair up with the Sky Patent Croc Point heel for ultimate Saturday night style! This profile boasts a black patent upper paired with a stiletto heel to really elongate those pins. Classy and chic - we love. ", brand: "Golden Shoe", color: "Black", price: "£30.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/111745/1117457040_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/111745/1117457040m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/111745/1117457040m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/111745/1117457040m7_zm.jpg"]),
    Product(favourited: false, productID: 27, filters: ["category": "womens", "type": "heels", "style": "casual courts"], shortDescription: "Natural Stacey Nude Patent Point High Heels", longDescription: "Make your Saturday night outfit pop with the Stacey Nude Patent Point heel! This chic profile boasts a natural patent upper that's versatile to match any weekend look. Sophisticated, chic and essential in any collection.", brand: "Golden Shoe", color: "Natural", price: "£25.00", onSale: true, salePrice: "£12.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/112553/1125531440_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/112553/1125531440m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/112553/1125531440m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/112553/1125531440m7_zm.jpg"]),
    Product(favourited: false, productID: 28, filters: ["category": "womens", "type": "heels", "style": "casual courts"], shortDescription: "Black Stacey Black Point High Heels", longDescription: "Freshen up your weekend look with the Stacey Black Point heel! This simple and chic profile arrives in a black fabric with a stiletto heel that'll take your look to new heights. These are perfect for Saturday night fun or weekday work. ", brand: "Golden Shoe", color: "Black", price: "£20.00", onSale: true, salePrice: "£9.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/112553/1125537070_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/112553/1125537070m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/112553/1125537070m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/112553/1125537070m7_zm.jpg"]),
    Product(favourited: false, productID: 29, filters: ["category": "womens", "type": "heels", "style": "party shoes"], shortDescription: "Black Sky Patent Croc Point High Heels", longDescription: "Pair up with the Sky Patent Croc Point heel for ultimate Saturday night style! This profile boasts a black patent upper paired with a stiletto heel to really elongate those pins. Classy and chic - we love. ", brand: "Golden Shoe", color: "Black", price: "£30.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/111745/1117457040_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/111745/1117457040m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/111745/1117457040m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/111745/1117457040m7_zm.jpg"]),
    Product(favourited: false, productID: 30, filters: ["category": "womens", "type": "heels", "style": "party shoes"], shortDescription: "Black Sia Metal Heel Peep Toe High Heels", longDescription: "Winter wardrobe planning? We're making it real easy! The Sia Metal Heel Peep Toe boot arrives in a black man-made upper sat on a stiletto heel to elevate any look. Classic, practical and definitely on our radar. ", brand: "Golden Shoe", color: "Black", price: "£32.00", onSale: true, salePrice: "£14.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/112555/1125557060_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/112555/1125557060m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/112555/1125557060m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/112555/1125557060m7_zm.jpg"]),
    Product(favourited: false, productID: 31, filters: ["category": "womens", "type": "heels", "style": "sling back"], shortDescription: "Gold Sasha Pointed Slingback High Heels", longDescription: "Looking for a real glam fit? We've got you covered! The Sasha Pointed Slingback heel boasts a gold man-made upper with a block heel to keep it comfortable but oh-so stylish. We rate. ", brand: "Golden Shoe", color: "Gold", price: "£28.00", onSale: true, salePrice: "£9.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/111744/1117442160_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/111744/1117442160m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/111744/1117442160m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/111744/1117442160m7_zm.jpg"]),
    Product(favourited: false, productID: 32, filters: ["category": "womens", "type": "heels", "style": "sling back"], shortDescription: "Black Sasha Pointed Slingback High Heels", longDescription: "It's officially the festive season and we're got the fit your wardrobe craves! The Sasha Pointed Slingback heel arrives in a black man-made upper sat on a block heel. This'll nail the trends this season, trust us.", brand: "Golden Shoe", color: "Black", price: "£28.00", onSale: true, salePrice: "£6.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/111744/1117447060_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/111744/1117447060m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/111744/1117447060m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/111744/1117447060m7_zm.jpg"]),
    Product(favourited: false, productID: 33, filters: ["category": "womens", "type": "heels", "style": "stilettos"], shortDescription: "Stacey Shimmer Point High Heels", longDescription: "The Stacey Shimmer Point heel has landed at Golden Shoe! This fit combines class and sophistication with unlimited sparkle that we know you'll love. You don't need anymore convincing. ", brand: "Golden Shoe", color: "Silver", price: "£25.00", onSale: true, salePrice: "£6.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/112553/1125537670_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/112553/1125537670m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/112553/1125537670m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/112553/1125537670m7_zm.jpg"]),
    Product(favourited: false, productID: 34, filters: ["category": "womens", "type": "heels", "style": "strappy"], shortDescription: "Bronze Sophia Metal Heel", longDescription: "Get glam this season with the Golden Shoe collection! The Sophia Metal Heel Sandal arrives in a brown man-made upper with a metallic finish for a real statement fit. Straps keep you secure while heel upgrades. ", brand: "Golden Shoe", color: "Bronze", price: "£30.00", onSale: true, salePrice: "£6.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/112554/1125546960_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/112554/1125546960m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/112554/1125546960m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/112554/1125546960m7_zm.jpg"]),
    Product(favourited: false, productID: 35, filters: ["category": "womens", "type": "heels", "style": "strappy"], shortDescription: "Black Sadie Strappy Mid Heel", longDescription: "Strappy heels? An essential in every glamorous wardrobe. The Sadie Strappy Mid Heel arrives in a black man-made upper in a cage silhouette for style you can't deny. Versatile, on-trend and on its way to your basket. ", brand: "Golden Shoe", color: "Black", price: "£25.00", onSale: true, salePrice: "£6.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/112556/1125567060_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/112556/1125567060m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/112556/1125567060m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/112556/1125567060m7_zm.jpg"]),
    Product(favourited: false, productID: 36, filters: ["category": "womens", "type": "heels", "style": "strappy"], shortDescription: "Silver Sadie Strappy Mid Heel", longDescription: "Glamorous, versatile and perfect for the festive season. The Sadie Strappy Mid Heel lands in a metallic silver man-made upper with a stiletto heel to elevate the look. We know you love. ", brand: "Golden Shoe", color: "Silver", price: "£25.00", onSale: true, salePrice: "£6.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/112556/1125567660_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/112556/1125567660m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/112556/1125567660m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/112556/1125567660m7_zm.jpg"]),
    Product(favourited: false, productID: 37, filters: ["category": "womens", "type": "sandals", "style": "flip flops"], shortDescription: "Pink You Shine Glitter Sandals", longDescription: "Get your summer fit with havaianas. The You Shine Metallic Glitter flip-flop boasts a pink man-made upper with a glittery finish for added shine and style. This simple fit is finished with havaianas branding.", brand: "Havaianas", color: "Pink", price: "£32.00", onSale: true, salePrice: "£19.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/176190/1761903560_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/176190/1761903560m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/176190/1761903560m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/176190/1761903560m7_zm.jpg"]),
    Product(favourited: false, productID: 38, filters: ["category": "womens", "type": "sandals", "style": "flip flops"], shortDescription: "Tan Tawney Sandals", longDescription: "Create a luxurious look this season wearing the sleek Tawney flip-flop. The chocolate tan colourway creates a versatile look while the leather strap and footbed create a comfortable stride. To finish, UGG branding and an EVA outsole keep things classy. ", brand: "UGG", color: "Tan", price: "£40.00", onSale: false, salePrice: "£25.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/177952/1779526220_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/177952/1779526220m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/177952/1779526220m7_zm.jpg"]),
    Product(favourited: false, productID: 39, filters: ["category": "womens", "type": "sandals", "style": "flip flops"], shortDescription: "Black & Silver Slim Carnival Sandals", longDescription: "A little sparkle never killed nobody, keep this in mind when strutting in the Slim Carnival silhouette as it arrives fresh from Havaianas. The black and silver glittering toe-post strap compliments the man-made footbed with a shimmery feel. ", brand: "Havaianas", color: "Black & Silver", price: "£28.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/176184/1761849960_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/176184/1761849960m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/176184/1761849960m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/176184/1761849960m7_zm.jpg"]),
    Product(favourited: false, productID: 40, filters: ["category": "womens", "type": "sandals", "style": "flip flops"], shortDescription: "White Popcat 20 Sandals", longDescription: "Lazy days or summer vacay - this fit will get you through! The PUMA Popcat 20 slider lands in a triple-white colourway in a man-made material. Signature PUMA branding completes the look.", brand: "PUMA", color: "White", price: "£22.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/171074/1710741060_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/171074/1710741060m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/171074/1710741060m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/171074/1710741060m7_zm.jpg"]),
    Product(favourited: false, productID: 41, filters: ["category": "womens", "type": "sandals", "style": "footbeds"], shortDescription: "Silver Flo Sandals", longDescription: "Landing in silver to jazz up our outfit, the Flor from Red or Dead is the sandal to spruce things up. Finished with buckled straps and a cork midsole, this on-trend style ticks all the boxes. ", brand: "Red Or Dead", color: "Silver", price: "£45.00", onSale: true, salePrice: "£14.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/177301/1773017620_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/177301/1773017620m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/177301/1773017620m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/177301/1773017620m7_zm.jpg"]),
    Product(favourited: false, productID: 42, filters: ["category": "womens", "type": "sandals", "style": "footbeds"], shortDescription: "Black Arizona Eva Sandals", longDescription: "Boasting an incredibly lightweight EVA construction, the man-made Arizona guarantees comfort all summer long. Dressed in all-black, for endless pairing, the classic Birkenstock sandal is complete with adjustable straps for a secure, custom fit. ", brand: "BIRKENSTOCK", color: "Black", price: "£35.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/174320/1743207060_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/174320/1743207060m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/174320/1743207060m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/174320/1743207060m7_zm.jpg"]),
    Product(favourited: false, productID: 43, filters: ["category": "womens", "type": "sandals", "style": "footbeds"], shortDescription: "Brown Gizeh Sandals", longDescription: "Hit the beach, shops or your favourite sunny spot with Birkenstock. The Gizeh is a thong style sandal with a brown manmade upper, cork latex footbed, adjustable buckled strap and shock absorbing EVA sole for comfort and durability. ", brand: "BIRKENSTOCK", color: "Brown", price: "£60.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/170045/1700456060_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/170045/1700456060m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/170045/1700456060m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/170045/1700456060m7_zm.jpg"]),
    Product(favourited: false, productID: 44, filters: ["category": "womens", "type": "sandals", "style": "footbeds"], shortDescription: "Brown Dominican Flatform Sandals", longDescription: "Your new season sandal collection won't be complete without some slick leopard print. The Dominican profile from our fresh Golden Shoe range boasts this trend on the man-made foot straps in brown and black while adjustable buckles and a 5cm flatform complete. ", brand: "Golden Shoe", color: "Brown", price: "£28.00", onSale: true, salePrice: "£21.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/173117/1731176060_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/173117/1731176060m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/173117/1731176060m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/173117/1731176060m7_zm.jpg"]),
    Product(favourited: false, productID: 45, filters: ["category": "womens", "type": "sandals", "style": "footbeds"], shortDescription: "Brown Aloha Sandals", longDescription: "This cork footbed sandal is giving us all the summer holiday vibes with its fierce design and strappy construction. The man-made Aloha arrives from our new season collection with brown and beige leopard print foot straps and an adjustable buckle.", brand: "Golden Shoe", color: "Brown", price: "£25.00", onSale: true, salePrice: "£18.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/173116/1731166060_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/173116/1731166060m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/173116/1731166060m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/173116/1731166060m7_zm.jpg"]),
    Product(favourited: false, productID: 46, filters: ["category": "womens", "type": "sandals", "style": "mules"], shortDescription: "Khaki Madrid Patent Sandals", longDescription: "Is summer your favourite season too? Complete your looks with the Birkenstock Madrid Patent. It boasts a khaki patent upper with a buckle strap. Sat on a cork-latex footbed and EVA outsole to keep it comfy. ", brand: "BIRKENSTOCK", color: "Khaki", price: "£50.00", onSale: true, salePrice: "£34.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/174327/1743274640_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/174327/1743274640m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/174327/1743274640m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/174327/1743274640m7_zm.jpg"]),
    Product(favourited: false, productID: 47, filters: ["category": "womens", "type": "sandals", "style": "mules"], shortDescription: "White London Leather Buckle Mule Sandals", longDescription: "Get summer ready with schuh! The London Leather Buckle Mule sandal boasts a white croc leather upper in a simple slip-on silhouette to make upgrading your look real easy.", brand: "Golden Shoe", color: "White", price: "£20.00", onSale: true, salePrice: "£9.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/173679/1736791020_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/173679/1736791020m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/173679/1736791020m7_zm.jpg"]),
    Product(favourited: false, productID: 48, filters: ["category": "womens", "type": "sandals", "style": "mules"], shortDescription: "White Madrid Sandals", longDescription: "This summer season, hit the beach, bar or boulevard in this editor-approved Madrid sandal from Birkenstock. The summer-ready profile features a white man-made single buckled strap for an understated aesthetic while a classic soft leather footbed finishes. ", brand: "Birkenstock", color: "White", price: "£50.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/170048/1700481060_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/170048/1700481060m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/170048/1700481060m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/170048/1700481060m7_zm.jpg"]),
    Product(favourited: false, productID: 49, filters: ["category": "womens", "type": "sandals", "style": "sandals"], shortDescription: "Red Paradise Slide Sandals", longDescription: "Everything looks better with a bow on top, facts are facts. So throw the TOMS Paradise Slide into the mix this season for a bold look. Bringing a red fabric upper strap to the party, flag branding and a man-made outsole complete the look. ", brand: "TOMS", color: "Red", price: "£45.00", onSale: true, salePrice: "£24.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/177871/1778713070_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/177871/1778713070m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/177871/1778713070m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/177871/1778713070m7_zm.jpg"]),
    Product(favourited: false, productID: 50, filters: ["category": "womens", "type": "sandals", "style": "sandals"], shortDescription: "White & Black Arizona Sandals", longDescription: "Get quirky with your style this season and choose the polka dot print Arizona sandal from Birkenstock. The white man-made foot straps are adorned with black spots while contrast yellow buckles complete. ", brand: "BIRKENSTOCK", color: "White & Black", price: "£70.00", onSale: false, salePrice: "£47.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/174353/1743531260_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/174353/1743531260m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/174353/1743531260m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/174353/1743531260m7_zm.jpg"]),
    Product(favourited: false, productID: 51, filters: ["category": "womens", "type": "sandals", "style": "sandals"], shortDescription: "White Classic Clog Sandals", longDescription: "Nobody freak out, Crocs are cool. Especially this triple-white Classic Clog. Classic branding and a handy heel strap make these a real statement. Are you brave enough to make it? We know if anyone can pull it off - its you. ", brand: "Crocs", color: "White", price: "£33.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/174800/1748001060_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/174800/1748001060m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/174800/1748001060m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/174800/1748001060m7_zm.jpg"]),
    Product(favourited: false, productID: 52, filters: ["category": "womens", "type": "sandals", "style": "sandals"], shortDescription: "Black Curly Sandals", longDescription: "Give your look some height with the PUBLIC DESIRE Curly. This wedged heel boasts a black man-made upper in a cage style silhouette to nail this seasons' trends. ", brand: "Public Desire", color: "Black", price: "£35.00", onSale: false, salePrice: "£9.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/176628/1766287060_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/176628/1766287060m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/176628/1766287060m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/176628/1766287060m7_zm.jpg"]),
    Product(favourited: false, productID: 53, filters: ["category": "womens", "type": "sandals", "style": "sandals"], shortDescription: "White Lisbon Tie Up Sandals", longDescription: "Get used to hearing ‘where did you get your shoes from?' as it'll come your way a lot when you're strutting around in these. The Lisbon tie up sandal from schuh in white looks fresh off the catwalk. ", brand: "Golden Shoe", color: "White", price: "£25.00", onSale: true, salePrice: "£6.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/173675/1736751060_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/173675/1736751060m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/173675/1736751060m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/173675/1736751060m7_zm.jpg"]),
    Product(favourited: false, productID: 54, filters: ["category": "womens", "type": "sandals", "style": "sports"], shortDescription: "White & Pink Croco Slide", longDescription: "Add the super-stylish Croco Slide 1193 into your rotation for a sweet finish to your look. The white and pink colourway gives a fun feel to this man-made slide while bold Lacoste branding adorns the strap and moulded footbed for a luxurious finish. ", brand: "Lacoste", color: "White & Pink", price: "£25.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/179303/1793032360_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/179303/1793032360m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/179303/1793032360m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/179303/1793032360m7_zm.jpg"]),
    Product(favourited: false, productID: 55, filters: ["category": "womens", "type": "sandals", "style": "sports"], shortDescription: "Black & White Croco Slide", longDescription: "Slide into some style this season and grab the Croco Slide 1193 from Lacoste for your collection. No matter what the weather, this black and white man-made slide will complete any look you're planning with stylish oversized branding across the strap. ", brand: "Lacoste", color: "Black & White", price: "£25.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/179303/1793037260_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/179303/1793037260m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/179303/1793037260m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/179303/1793037260m7_zm.jpg"]),
    Product(favourited: false, productID: 56, filters: ["category": "womens", "type": "sandals", "style": "sports"], shortDescription: "White & Silver Filippo Sandals", longDescription: "Add some chic influence to your poolside looks this season and grab the ellesse Filippo slide asap. Crafted with a white and silver colourway, this man-made footbed poolslide is a loungewear staple this season. Big branding finishes with a 90s feel. ", brand: "Ellesse", color: "White & Silver", price: "£23.00", onSale: true, salePrice: "£16.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/179056/1790561860_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/179056/1790561860m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/179056/1790561860m7_zm.jpg"]),
    Product(favourited: false, productID: 57, filters: ["category": "womens", "type": "slippers"], shortDescription: "Black Fluff Yeah Slide Slippers", longDescription: "Delivering ultra-comfortable glam slipper style, the UGG Fluff Yeah Slide arrives. Boasting a black sheepskin upper for cosy wear, this slipper features an elastic heel strap with oversized UGG branding. A 5cm raised footbed gives this look a lift. ", brand: "UGG", color: "Black", price: "£100.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/160161/1601617020_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/160161/1601617020m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/160161/1601617020m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/160161/1601617020m7_zm.jpg"]),
    Product(favourited: false, productID: 58, filters: ["category": "womens", "type": "slippers"], shortDescription: "Peach Scuffette Slippers", longDescription: "Cosy, cute and definitely on our wish-list! The UGG Scuffette slipper lands in a peach suede upper lined with UGGPureWool for all the warmth your toes need. You know these won't be around for long ", brand: "UGG", color: "Peach", price: "£80.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/160150/1601502950_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/160150/1601502950m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/160150/1601502950m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/160150/1601502950m7_zm.jpg"]),
    Product(favourited: false, productID: 59, filters: ["category": "womens", "type": "slippers"], shortDescription: "Natural Hayley Faux Fur Slippers", longDescription: "It's time to get cosy. The Hayley Faux Fur Slipper arrives in a natural colourway with plenty of fluffy fabric to keep those toes warm. We love this fit. ", brand: "Golden Shoe", color: "Natural", price: "£15.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/160001/1600011470_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/160001/1600011470m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/160001/1600011470m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/160001/1600011470m7_zm.jpg"]),
    Product(favourited: false, productID: 60, filters: ["category": "womens", "type": "slippers"], shortDescription: "Black Hope Faux Fur Slippers", longDescription: "Cosy winter fits just got stylish! The OO Hope Faux Fur Slipper arrives to warm those toes in a black colourway to match all your favourite PJs. Comfy, on-trend and perfect for any loungewear look. ", brand: "Golden Shoe", color: "Black", price: "£15.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/160130/1601307070_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/160130/1601307070m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/160130/1601307070m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/160130/1601307070m7_zm.jpg"]),
    Product(favourited: false, productID: 61, filters: ["category": "womens", "type": "slippers"], shortDescription: "Grey Hope Faux Fur Slippers", longDescription: "Treat those feet to the OO Hope Faux Fur Slipper! This slip-on style boasts a grey faux-fur upper that's real soft and cosy for those winter movie days. Nail your loungewear look now! ", brand: "Golden Shoe", color: "Grey", price: "£15.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/160130/1601307570_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/160130/1601307570m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/160130/1601307570m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/160130/1601307570m7_zm.jpg"]),
    Product(favourited: false, productID: 62, filters: ["category": "womens", "type": "trainers", "style": "alternative"], shortDescription: "Black Burst Very Daring Trainers", longDescription: "Every day, on-the-go comfort is what Skechers are renowned for. Keeping up with the hype, is their Burst Very Daring silhouette, a sporty stylish sneaker in triple black. The fabric style sits on top of a Burst Compound midsole for a supportive wear.", brand: "SKECHERS", color: "Black", price: "£56.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/191540/1915407070_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/191540/1915407070m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/191540/1915407070m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/191540/1915407070m7_zm.jpg"]),
    Product(favourited: false, productID: 63, filters: ["category": "womens", "type": "trainers", "style": "alternative"], shortDescription: "White & Gold Chuck Taylor All Star", longDescription: "Crafted to give your new season wardrobe a crisp and charming finish; Converse update this classic profile with glam gold eyelets and branding. The Chuck Taylor All Star Craft Ox features a glossy white man-made upper and original vulcanised outsole. ", brand: "Converse", color: "White & Gold", price: "£62.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/192425/1924251960_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/192425/1924251960m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/192425/1924251960m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/192425/1924251960m7_zm.jpg"]),
    Product(favourited: false, productID: 64, filters: ["category": "womens", "type": "trainers", "style": "alternative"], shortDescription: "Khaki Finesse Trainers", longDescription: "Keep it cool in khaki with this fashion-forward sneaker from our very own schuh collection and complete any look with statement Finesse. The man-made profile boasts a one-piece upper with camouflage inserts and a black elastic strap detail completing. ", brand: "Golden Shoe", color: "Khaki", price: "£45.00", onSale: true, salePrice: "£30.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/132631/1326314660_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/132631/1326314660m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/132631/1326314660m7_zm.jpg"]),
    Product(favourited: false, productID: 65, filters: ["category": "womens", "type": "trainers", "style": "core classic"], shortDescription: "Red All Start Hi Trainers", longDescription: "The Converse All Star Hi is an absolute classic and a favourite here at schuh. The red canvas upper bears the original Chuck Taylor badge on the inner ankle and sits on a rubber vulcanised sole with toe cap. As cool now as it ever was. ", brand: "Converse", color: "Red", price: "£57.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/192249/1922493070_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/192249/1922493070m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/192249/1922493070m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/192249/1922493070m7_zm.jpg"]),
    Product(favourited: false, productID: 66, filters: ["category": "womens", "type": "trainers", "style": "core classic"], shortDescription: "Navy & White All Start Oxford Trainers", longDescription: "The iconic plimsoll from Converse arrives in a timeless navy and white colourway. The All Star Oxford stays true to its roots, with classic details such as a crisp canvas upper, rubber toe cap and vulcanised sole unit. Branding completes. ", brand: "Converse", color: "Navy & White", price: "£52.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/190272/1902725970_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/190272/1902725970m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/190272/1902725970m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/190272/1902725970m7_zm.jpg"]),
    Product(favourited: false, productID: 67, filters: ["category": "womens", "type": "trainers", "style": "fashion sports"], shortDescription: "White Nite Jogger Trainers", longDescription: "Bringing those futuristic vibes into your rotation for a new season boost, the Nite Jogger arrives from adidas. The white sneaker features a man-made and mesh mix upper with reflective accents and sporty details. ", brand: "Adidas", color: "White", price: "£100.00", onSale: true, salePrice: "£64.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/192156/1921561060_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/192156/1921561060m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/192156/1921561060m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/192156/1921561060m7_zm.jpg"]),
    Product(favourited: false, productID: 68, filters: ["category": "womens", "type": "trainers", "style": "fashion sports"], shortDescription: "White & Pink Nizza Platform Trainers", longDescription: "Upgrade your white kick collection with a classic! The adidas Nizza Platform trainer boasts a white and pink fabric upper sat on a chunky rubber outsole for statement style. We know you'll rate. ", brand: "Adidas", color: "White & Pink", price: "£50.00", onSale: true, salePrice: "£34.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/192152/1921522370_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/192152/1921522370m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/192152/1921522370m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/192152/1921522370m7_zm.jpg"]),
    Product(favourited: false, productID: 69, filters: ["category": "womens", "type": "trainers", "style": "fashion sports"], shortDescription: "Black & Purple Arch Fit Trainers", longDescription: "Upgrade your running sneaker collection with Skechers! The Arch Fit trainer boasts a black and pink fabric with an Air Cooled Memory Foam insole for ultimate comfort. Complete with branding embossed.", brand: "SKECHERS", color: "Black & Purple", price: "£77.00", onSale: true, salePrice: "£54.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/191788/1917888970_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/191788/1917888970m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/191788/1917888970m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/191788/1917888970m7_zm.jpg"]),
    Product(favourited: false, productID: 70, filters: ["category": "womens", "type": "trainers", "style": "fashion sports"], shortDescription: "Black & Gold Charged Rogue 2 Storm Trainers", longDescription: "Step up your running game with the Under Armour Charged Rogue 2 Storm! Boasting a black and gold man-made upper paired with a UA Plush sockliner for tailored comfort. Charged Cushioning provides energy in every step - this really is a no-brainer. ", brand: "Under Armour", color: "Black & Gold", price: "£75.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/197924/1979247960_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/197924/1979247960m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/197924/1979247960m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/197924/1979247960m7_zm.jpg"]),
    Product(favourited: false, productID: 71, filters: ["category": "womens", "type": "trainers", "style": "fashion sports"], shortDescription: "Black & White Nizza Platform Trainers", longDescription: "This Nizza from adidas is fitted with a platform sole, classic 3-stripe branding, a chic black colourway and toe-cap detailing. Everything you could ever want from your new pair, if you ask us. ", brand: "Adidas", color: "Black & White", price: "£50.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/192152/1921527270_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/192152/1921527270m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/192152/1921527270m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/192152/1921527270m7_zm.jpg"]),
    Product(favourited: false, productID: 72, filters: ["category": "womens", "type": "trainers", "style": "fashion sports"], shortDescription: "White & Pink Charged Breath Lace Trainers", longDescription: "Running your thing? Oh, we've got you covered! The Under Armour Charged Breath Lace lands in a white and pink man-made upper sat on Charged Cushioning to add energy to every step. Branding completes. ", brand: "Under Armour", color: "White & Pink", price: "£65.00", onSale: true, salePrice: "£39.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/197926/1979262360_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/197926/1979262360m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/197926/1979262360m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/197926/1979262360m7_zm.jpg"]),
    Product(favourited: false, productID: 73, filters: ["category": "womens", "type": "trainers", "style": "fitness"], shortDescription: "White & Pink U Path Trainers", longDescription: "Let's talk sneakers. The adidas U Path breaks into the scene in a white and pink fabric upper sat on a flexible and lightweight rubber outsole to keep you on the move. Running or casual wear - this fit provides. ", brand: "Adidas", color: "White & Pink", price: "£70.00", onSale: true, salePrice: "£41.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/192111/1921112370_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/192111/1921112370m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/192111/1921112370m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/192111/1921112370m7_zm.jpg"]),
    Product(favourited: false, productID: 74, filters: ["category": "womens", "type": "trainers", "style": "fitness"], shortDescription: "White Andrige Trainers", longDescription: "Update your sneaker collection with the adidas Andrige! Boasting a white man-made upper sat on an EVA and TPU midsole for all day comfort guaranteed. Lightweight, breathable and perfect for any occasion.", brand: "Adidas", color: "White", price: "£75.00", onSale: true, salePrice: "£34.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/192107/1921071060_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/192107/1921071060m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/192107/1921071060m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/192107/1921071060m7_zm.jpg"]),
    Product(favourited: false, productID: 75, filters: ["category": "womens", "type": "trainers", "style": "fitness"], shortDescription: "White & Black Superstar Foundation Trainers", longDescription: "A retro Superstar Foundation makes a comeback, as the classic adidas silhouette arrives in a cool monochrome colourway. The crisp white leather upper features black 3-stripe branding and accents, with the famous shell toe cap completing nicely. ", brand: "Adidas", color: "White & Black", price: "£75.00", onSale: true, salePrice: "£49.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/191991/1919911220_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/191991/1919911220m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/191991/1919911220m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/191991/1919911220m7_zm.jpg"]),
    Product(favourited: false, productID: 76, filters: ["category": "womens", "type": "trainers", "style": "fitness"], shortDescription: "Black & White Internationalist Trainers", longDescription: "The perfect trainer for trotting the globe, the Nike Internationalist arrives at schuh. Boasting a black and grey man-made upper, this profile has waterproof and suede overlays while Swoosh branding and a beige rubber sole give a classic feel. ", brand: "Nike", color: "Black & White", price: "£80.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/196043/1960437270_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/196043/1960437270m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/196043/1960437270m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/196043/1960437270m7_zm.jpg"]),
    Product(favourited: false, productID: 77, filters: ["category": "womens", "type": "trainers", "style": "fitness"], shortDescription: "Grey Flex Appeal 3.0 Trainers", longDescription: "This jersey fabric walking sneaker is a perfect option for your weekday collection. Arriving from Skechers, the Flex Appeal 3.0 boasts a versatile grey upper for easy styling while sidewall branding and complimenting pale pink lacing completes the look.", brand: "SKECHERS", color: "Grey", price: "£59.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/191742/1917427570_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/191742/1917427570m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/191742/1917427570m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/191742/1917427570m7_zm.jpg"]),
    Product(favourited: false, productID: 78, filters: ["category": "womens", "type": "trainers", "style": "hi tops"], shortDescription: "Black All Start Hi Trainers", longDescription: "The Converse All Star Hi is an absolute classic and a favourite here at schuh. The crisp black canvas upper bears the original Chuck Taylor badge on the inner ankle and sits on a rubber vulcanised sole with a classic rubber toe cap completing. ", brand: "Converse", color: "Black", price: "£57.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/190032/1900327070_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/190032/1900327070m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/190032/1900327070m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/190032/1900327070m7_zm.jpg"]),
    Product(favourited: false, productID: 79, filters: ["category": "womens", "type": "trainers", "style": "hi tops"], shortDescription: "White Cons Move Platform Hi Trainers", longDescription: "Upgrade your Converse collection with the Chuck Taylor All Star Move Platform! This slick remix on the classic arrives in a white fabric upper with a chunky platform sole that we know you'll rate. Complete with branding. ", brand: "Converse", color: "White", price: "£70.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/192314/1923141070_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/192314/1923141070m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/192314/1923141070m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/192314/1923141070m7_zm.jpg"]),
    Product(favourited: false, productID: 80, filters: ["category": "womens", "type": "trainers", "style": "hi tops"], shortDescription: "White & Black Hi Logo Play Trainers", longDescription: "The originals have remixed to create the unimaginable. Arriving as part of the Converse Twisted collection, this Chuck Taylor All Star Hi Logo Play boasts a white fabric upper with 4 branded badges and 2 license plates for standout style. Switch it up. ", brand: "Converse", color: "White & Black", price: "£65.00", onSale: true, salePrice: "£47.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/192243/1922431270_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/192243/1922431270m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/192243/1922431270m7_zm.jpg"]),
    Product(favourited: false, productID: 81, filters: ["category": "womens", "type": "trainers", "style": "hi tops"], shortDescription: "Pale Pink Blazer Mid Vntg 77", longDescription: "These iconic kicks never go out of style, trust us. The Nike Blazer Mid VNTG 77 lands in a pale pink suede upper paired with the iconic 90s varsity silhouette that lines the streets across the globe. ", brand: "Nike", color: "Pale Pink", price: "£90.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/195068/1950683350_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/195068/1950683350m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/195068/1950683350m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/195068/1950683350m7_zm.jpg"]),
    Product(favourited: false, productID: 82, filters: ["category": "womens", "type": "trainers", "style": "skate"], shortDescription: "Black & White Classic Slip-On Mix Checker Trainers", longDescription: "Bringing your authentic skate style to life, Vans deliver the Classic Slip-On with a modern Mix Checker pattern adorning. The black and white fabric upper features panels of signature checkerboard in varying sizes for a stylish new season update. ", brand: "Vans", color: "Black & White", price: "£55.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/197462/1974627270_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/197462/1974627270m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/197462/1974627270m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/197462/1974627270m7_zm.jpg"]),
    Product(favourited: false, productID: 83, filters: ["category": "womens", "type": "trainers", "style": "skate"], shortDescription: "Black & White Charge Trainers", longDescription: "Get your skate style locked down with the Nike SB Charge. The black silhouette with white detailing features Swoosh branding and a solid vulc outsole to help you get your skating all day long. ", brand: "Nike SB", color: "Black & White", price: "£50.00", onSale: false, salePrice: nil, imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/196200/1962007270_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/196200/1962007270m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/196200/1962007270m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/196200/1962007270m7_zm.jpg"]),
    Product(favourited: false, productID: 84, filters: ["category": "womens", "type": "trainers", "style": "skate"], shortDescription: "Pale Blue Charge Trainers", longDescription: "It's time to upgrade and we've got the fit! The Nike SB Charge boasts a pale blue fabric upper with a contrasting white rubber sole for a real fresh finish. This simple style is a staple in any collection. ", brand: "Nike SB", color: "Pale Blue", price: "£50.00", onSale: true, salePrice: "£31.99", imagesURL: ["https://d2ob0iztsaxy5v.cloudfront.net/product/196203/1962035370_main.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/196203/1962035370m3_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/196203/1962035370m4_zm.jpg", "https://d2ob0iztsaxy5v.cloudfront.net/product/196203/1962035370m7_zm.jpg"])
  ]

  // MARK: - Singleton Instance
  static let shared = Products()

  var filteredProducts: [Product]
  var searchableProducts: [Product]

  private lazy var formatter: NumberFormatter = {
    let formatter = NumberFormatter()
    let locale = Locale(identifier: "en_GB")
    formatter.numberStyle = .currency
    formatter.locale = locale
    return formatter
  }()

  var brandCounts: [(key: String, value: Int)] {
    var brandCounts = [String: Int]()
    filteredProducts.forEach {
      if brandCounts.keys.contains($0.brand) {
        brandCounts[$0.brand]! += 1
      } else {
        brandCounts[$0.brand] = 1
      }
    }
    let sortedBrands = brandCounts.sorted { $0.key.localizedStandardCompare($1.key) == .orderedAscending }
    return sortedBrands
  }

  var colorCounts: [(key: String, value: Int)] {
    var colorCounts = [String: Int]()
    filteredProducts.forEach {
      if colorCounts.keys.contains($0.color) {
        colorCounts[$0.color]! += 1
      } else {
        colorCounts[$0.color] = 1
      }
    }
    let sortedColors = colorCounts.sorted { $0.key.localizedStandardCompare($1.key) == .orderedAscending }
    return sortedColors
  }

  var saleCounts: [String: Int] {
    var saleCounts = ["On Sale": 0, "Not On Sale": 0]
    filteredProducts.forEach {
      if $0.onSale {
        saleCounts["On Sale"]! += 1
      } else {
        saleCounts["Not On Sale"]! += 1
      }
    }
    return saleCounts
  }

  var minProductPrice: Float {
    var minPrice = Float.infinity
    filteredProducts.forEach {
      if $0.onSale, let numPrice = formatter.number(from: $0.salePrice!)?.floatValue {
        minPrice = min(minPrice, numPrice)
      } else if !$0.onSale, let numPrice = formatter.number(from: $0.price)?.floatValue {
        minPrice = min(minPrice, numPrice)
      }
    }
    return minPrice
  }

  var maxProductPrice: Float {
    var maxPrice: Float = 0.0
    filteredProducts.forEach {
      if $0.onSale, let numPrice = formatter.number(from: $0.salePrice!)?.floatValue {
        maxPrice = max(maxPrice, numPrice)
      } else if !$0.onSale, let numPrice = formatter.number(from: $0.price)?.floatValue {
        maxPrice = max(maxPrice, numPrice)
      }
    }
    return maxPrice
  }

  private init() {
    filteredProducts = products
    searchableProducts = products
  }

  func filterBy(criteria: [String: String]?) {
    guard let criteria = criteria else {
      filteredProducts = products
      return
    }
    filteredProducts = products.filter { product in
      switch criteria.count {
      case 1: return product.filters["category"] == criteria["category"]
      case 2:
        return product.filters["category"] == criteria["category"]
          && product.filters["type"] == criteria["type"]
      case 3: return product.filters == criteria
      default: fatalError("Undefined Filter Config")
      }
    }
    searchableProducts = filteredProducts
  }

  func filterBy(searchTerm: String) {
    guard !searchTerm.isEmpty else {
      filteredProducts = searchableProducts
      return
    }
    let lowercasedSearch = searchTerm.lowercased().trimmingCharacters(in: .whitespaces)
    filteredProducts = searchableProducts.filter {
      $0.shortDescription.lowercased().contains(lowercasedSearch)
        || $0.longDescription.lowercased().contains(lowercasedSearch)
        || $0.brand.lowercased().contains(lowercasedSearch)
        || $0.color.lowercased().contains(lowercasedSearch)
    }
  }

  // swiftlint:disable cyclomatic_complexity
  func filterBy(_ filters: [FilterTypes: [String]]) {
    for type in FilterTypes.allCases {
      guard let myFilters = filters[type] else { return }
      if !myFilters.isEmpty {
        switch type {
        case .brand:
          filteredProducts = filteredProducts.filter { myFilters.contains(where: $0.brand.contains) }
        case .color:
          filteredProducts = filteredProducts.filter { myFilters.contains(where: $0.color.contains) }
        case .sale:
          if !(myFilters.contains("On Sale") && myFilters.contains("Not On Sale")) {
            if myFilters.contains("On Sale") {
              filteredProducts = filteredProducts.filter { $0.onSale }
            } else if myFilters.contains("Not On Sale") {
              filteredProducts = filteredProducts.filter { !$0.onSale }
            }
          }
        case .price:
          let minPrice = formatter.number(from: myFilters[0])!.floatValue
          let maxPrice = formatter.number(from: myFilters[1])!.floatValue
          filteredProducts = filteredProducts.filter {
            if $0.onSale {
              let salePrice = formatter.number(from: $0.salePrice!)!.floatValue
              return (salePrice > minPrice) && (salePrice < maxPrice)
            } else {
              let salePrice = formatter.number(from: $0.price)!.floatValue
              return salePrice > minPrice && salePrice < maxPrice
            }
          }
        }
      }
      searchableProducts = filteredProducts
    }
  }

  func sortBy(sortType: SortTypes?) {
    guard let sortType = sortType else {
      filteredProducts.sort { $0.productID < $1.productID }
      return
    }
    switch sortType {
    case .nameAToZ: filteredProducts.sort {
      $0.shortDescription.localizedStandardCompare($1.shortDescription) == .orderedAscending
    }
    case .nameZToA: filteredProducts.sort {
      $0.shortDescription.localizedStandardCompare($1.shortDescription) == .orderedDescending
    }
    case .priceHighToLow: filteredProducts.sort {
      $0.price.localizedStandardCompare($1.price) == .orderedDescending
    }
    case .priceLowToHigh: filteredProducts.sort {
      $0.price.localizedStandardCompare($1.price) == .orderedAscending
    }
    }
  }
}
